import { useState } from "react";
import Head from "next/head";
import { Box } from "@chakra-ui/react";
import Navbar from "@/common/components/Navbar/Navbar";
import MoviesContainer from "@/common/components/MoviesContainer/MoviesContainer";

export default function Home() {
  const [searchTerm, setSearchTerm] = useState("");

  const onHandleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchTerm(e.target.value.trim());
  };

  return (
    <>
      <Head>
        <title>Movie Marker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar onHandleChange={onHandleChange} />
        <Box mt="100">
          <MoviesContainer searchTerm={searchTerm} />
        </Box>
      </main>
    </>
  );
}
